title: Local Infra
language: en
theme: dark
color: slate
target: _self
hideVersion: true
layout:
  Platform:
    style: row
    columns: 3
  Observability:
    style: row
    columns: 3
  Apps:
    style: row
    columns: 3
